version: '3.7'
services:
  mavlink-tag-controller:
    image:          mavlink-tag-controller:#VERSION#
    container_name: mavlink-tag-controller
    restart:        unless-stopped
    network_mode:   host
    volumes:
      - '/data/app/mavlink-tag-controller/data:/data'
